### PR TITLE
Port blog page.

### PR DESCRIPTION
**Pull request by maxlazio**
Part of https://github.com/git/git-scm.com/issues/942 .

### CODE REVIEW

**Comment by spraints** [comment]
@maxlazio I noticed a couple of things, while comparing a local copy of this to git-scm.com.

The blog post urls look like `http://127.0.0.1:4000/2010/03/04/smart-http.html` instead of `https://git-scm.com/blog/2010/03/04/smart-http.html`. I think it's a pretty simple change to `_config.yml` to set the permalink for all of them?

Also, the styles for some of the `<pre>` (?) elements is off.
git-scm.com:

screen shot 2017-02-09 at 8 03 45 pm

this branch:

screen shot 2017-02-09 at 8 03 38 pm

I'm not in love with either style, tbh, but it'd be nice to match what's there or make it look a little better.

**Comment by peff** [comment]
I actually wonder if we should drop the blog posts entirely. They're quite old at this point, and my understanding is that the original purpose was to act as a sort of ongoing addendum to Pro Git. But since they were written, Pro Git 2 was published, which should have incorporated that content.

@ben @schacon Any thoughts on that?

**Comment by ben** [comment]
Yeah, we tried to grab the best content and integrate it into the 2nd edition of the book. The ["three trees" post](https://git-scm.com/blog/2011/07/11/reset.html), for instance, became [section 7.7](https://git-scm.com/book/en/v2/Git-Tools-Reset-Demystified).

I'm totally cool with dropping them for all the reasons @peff said, but @schacon's opinion probably matters more than mine here.

**Comment by maxlazio** [comment]
@spraints I'll hold of from improvements until we get a decision about whether the page is even necessary.

**Comment by peff** [comment]
I'm not sure if we'll hear from @schacon or not. So I'll make an executive decision: let's drop the blog posts going forward. If there's good content in them that isn't covered elsewhere, I'd much rather see it rolled into the book or into Git's manpages.

I'm not sure if we should do something for people linking to them, so they don't just get a 404. Maybe just a page that says "hey, go read Pro Git" with a link to the book.

**Comment by maxlazio** [comment]
Allright, blog can be skipped then :) I've left the main blog page in case someone ends up there from old links.

**Comment by spraints** [comment]
😎

**Comment by peff** [comment]
> I've left the main blog page in case someone ends up there from old links.

That sounds good. We could also put redirects for all the old page names, but I'm happy for that to come later (or never) when somebody complains.

**Pull request merged**
